# SciPy

###### 1. Interacting with NumPy
###### 2. Linear algebra

In [ ]:
# from scipy import linalg, sparse
import scipy
import numpy as np

help(scipy.linalg.diagsvd)  # Asking For Help
np.info(np.matrix)          # Asking For Help

# 1. Interacting With NumPy

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([(1+5j,2j,3j), (4j,5j,6j)])
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])

### Index Tricks

In [ ]:
np.mgrid[0:5,0:5]          # Create a dense meshgrid 5x5 0-5 values
np.ogrid[0:2,0:2]          # Create an open meshgrid
np.r_[[3,[0]*5,-1:1:10j]   # Stack arrays vertically (row-wise) ????
np.c_[b,c]                 # Create stacked column-wise arrays

### Shape Manipulation

In [ ]:
np.transpose(b)            # Permute array dimensions
b.flatten()                # Flatten the array
np.hstack((b,c))           # Stack arrays horizontally (column-wise)
np.vstack((a,b))           # Stack arrays vertically (row-wise)
np.hsplit(c,2)             # Split the array horizontally at the 2nd index
np.vpslit(d,2)             # Split the array vertically at the 2nd index

### Polynomials

In [145]:
from numpy import poly1d
p = poly1d([3,4,5])        # Create a polynomial object

### Vectorizing Functions

In [151]:
def myfunc(a):
    if a < 0:
        return a*2
    else:
        return a/2
    
np.vectorize(myfunc)

### Type Handling

In [ ]:
np.real(c)                    # Return the real part of the array elements
np.imag(c)                    # Return the imaginary part of the array elements
np.real_if_close(c,tol=1000)  # Return a real array if complex parts close to 0
np.cast['f'](np.pi)           # Cast object to a data type

### Other Useful Functions

In [ ]:
np.angle(b,deg=True)               # Return the angle of the complex argument
g = np.linspace(0,np.pi,num=5)     # Create an array of evenly spaced values (log scale)
g [3:] += np.pi                    # ?
np.unwrap(g)                       # Unwrap
np.logspace(0,10,3)                # Create an array of evenly spaced values (log scale)
np.select([c<4],[c*2])             # Return values from a list of arrays depending on conditions
misc.factorial(a)                  # Factorial
misc.comb(10,3,exact=True)         # Combine N things taken at k time
misc.central_diff_weights(3)       # Weights for Np-point central derivative
misc.derivative(myfunc,1.0)        # Find the n-th derivative of a function at a point

# 2. Linear Algebra

### Creating Matrices

In [235]:
A = np.matrix(np.random.random((2,2)))
B = np.asmatrix(a)
C = np.mat(np.random.random((10,5)))
D = np.mat([[3,4], [5,6]])

print(A)
print(B)
print(C)
print(D)


[[ 0.10677329  0.53457286]
 [ 0.45805979  0.28209882]]
[[ 4  8  4]
 [ 8 12 16]
 [16 12  8]]
[[ 0.18954053  0.80058475  0.12982368  0.25933098  0.27671746]
 [ 0.77678782  0.37236151  0.87351839  0.28564743  0.16935857]
 [ 0.79576032  0.23486282  0.60165423  0.8459612   0.51335859]
 [ 0.03565535  0.40095014  0.94799811  0.74718507  0.99615887]
 [ 0.52747965  0.53135385  0.11024549  0.98614772  0.42127892]
 [ 0.04731574  0.13592969  0.76467734  0.29609281  0.42605445]
 [ 0.250335    0.17151121  0.84690327  0.9110324   0.23805794]
 [ 0.82237441  0.61236111  0.44538652  0.5610266   0.7948872 ]
 [ 0.86832619  0.32145005  0.17504379  0.25419191  0.20195734]
 [ 0.37371748  0.01786672  0.27782123  0.91079309  0.91007485]]
[[3 4]
 [5 6]]


### Basic Matrix Routines

##### Inverse

In [242]:
A.I                # Inverse
linalg.inv(A)      # Inverse
A.T                # Tranpose matrix
A.H                # Conjugate transposition
np.trace(A)        # Trace

print(A)
print(A.I)
print(linalg.inv(A))
print(A.T)
print(A.H)
print(np.trace(A))

[[ 0.10677329  0.53457286]
 [ 0.45805979  0.28209882]]
[[-1.31364121  2.48932961]
 [ 2.13303346 -0.49720803]]
[[-1.31364121  2.48932961]
 [ 2.13303346 -0.49720803]]
[[ 0.10677329  0.45805979]
 [ 0.53457286  0.28209882]]
[[ 0.10677329  0.45805979]
 [ 0.53457286  0.28209882]]
0.388872109237


##### Norm

In [ ]:
linalg.norm(A)          # Frobenius norm
linalg.norm(A,1)        # L1 norm (max column sum)
linalg.norm(A,np.inf)   # L inf norm (max row sum)

##### Rank

In [ ]:
np.linalg.matrix_rank(C)    # Matrix rank

##### Determinant

In [ ]:
inalg.det(A)                # Determinant

##### Solving linear problems

In [ ]:
linalg.solve(A,b)          # Solver for dense matrices
E = np.mat(a).T            # Solver for dense matrices
linalg.lstsq(D,E)          # Solver for dense matrices equation

##### Generalized inverse

In [ ]:
linalg.pinv(C)      # Compute the pseudo-inverse of a matrix (least-squares solver)
linalg.pinv2(C)     # Compute the pseudo-inverse of a matrix (SVD)

### Creating Sparse Matrices

In [ ]:
F = np.eye(3, k=1)          # Create a 2X2 identity matrix
G = np.mat(np.identity(2))  # Create a 2x2 identity matrix
C[C > 0.5] = 0              # bez opisu
H = sparse.csr_matrix(C)    # Compressed Sparse Row matrix
I = sparse.csc_matrix(D)    # Compressed Sparse Column matrix
J = sparse.dok_matrix(A)    # Dictionary Of Keys matrix
E.todense()                 # Sparse matrix to full matrix
sparse.isspmatrix_csc(A)    # Identify sparse matrix








### Sparse Matrix Routines

In [ ]:
sparse.linalg.inv(I)         # Inverse
sparse.linalg.norm(I)        # Norm
sparse.linalg.spsolve(H,I)   # Solver for sparse matrices

### Sparse Matrix Functions

In [ ]:
sparse.linalg.expm(I)        # Sparse matrix exponential

### Matrix Functions

##### Addition

In [ ]:
np.add(A,D)

##### Subtraction

In [ ]:
np.subtract(A,D)

##### Division

In [ ]:
np.divide(A,D)

##### Multiplication

In [ ]:
np.multiply(D,A)          # Multiplication
np.dot(A,D)               # Dot product
np.vdot(A,D)              # Vector dot product
np.inner(A,D)             # Inner product
np.outer(A,D)             # Outer product
np.tensordot(A,D)         # Tensor dot product
np.kron(A,D)              # Kronecker product

##### Exponential Functions

In [ ]:
linalg.expm(A)       # Matrix exponential
linalg.expm2(A)      # Matrix exponential (Taylor Series)
linalg.expm3(D)      # Matrix exponential (eigenvalue decomposition)

##### Logarithm Function

In [ ]:
linalg.logm(A)       # Matrix logarithm

##### Trigonometric Tunctions

In [ ]:
linalg.sinm(D)      # Hypberbolic matrix sine
linalg.cosm(D)      # Hyperbolic matrix cosine
linalg.tanm(A)      # Hyperbolic matrix tangent

##### Hyperbolic Trigonometric Functions

In [ ]:
np.sigm(A)          # Matrix sign function

##### Matrix Sign Function

In [ ]:
linalg.sqrtm(A)     # Matrix square root

##### Matrix Square Root

In [ ]:
linalg.sqrtm(A)     # Matrix square root

##### Arbitrary Functions

In [ ]:
linalg.funm(A, lambda x: x*x)    # Evaluate matrix function

### Decompositions

##### Eigenvalues and Eigenvectors

In [ ]:
la, v = linalg.eig(A)    # Solve ordinary or generalized eigenvalue problem for square matrix
l1, l2 = la              # Unpack eigenvalues 
v[:,0]                   # First eigenvector
v[:,1]                   # Second eigenvector
linalg.eigvals(A)        # Unpack eigenvalues

##### Singular Value Decomposition

In [ ]:
U,s,Vh = linalg.svd(B)          # Singular Value Decomposition (SVD)
M,N = B.shape                   # bez opisu
Sig = linalg.diagsvd(s,M,N)     # Construct sigma matrix in SVD


##### LU Decomposition

In [ ]:
P,L,U = linalg.lu(C)

### Sparse Matrix Decompositions

In [ ]:
la, v = sparse.linalg.eigs(F,1)   # ?
parse.linalg.svds(H, 2)           # Eigenvalues and eigenvectors SVD